version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: async-system-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:15
    container_name: async-system-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asyncflow
